# @package experiment.config

do_train: false
train_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - 002_cube_tbp
  - 004_cube_numenta
  - 012_cylinder_tbp_horz
  - 014_cylinder_numenta_horz
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.RandomRotation
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}

