# @package experiment.config

do_train: true
train_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - 002_cube_tbp
  - 004_cube_numenta
  - 012_cylinder_tbp_horz
  - 013_cylinder_tbp_vert
  - 014_cylinder_numenta_horz
  - 015_cylinder_numenta_vert
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations: ${constants.rotations_all}
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
